### PR TITLE
Convert buffer to string before parsing

### LINKED ISSUE #166: Convert buffer before parsing via JSON.parse
## Steps to reproduce the issue

1. Open file in editor
2. Read editor error

## Expected result

Error doesn't see in editor.

## Actual result

Error is occured in editor.

## Other details

I use VSC.

Version of package: ??

Browser: ??

Operating system: ??

### PR DESCRIPTION
**Pull request by piecioshka**
Fixes #166 

Description of proposed changes:

- Convert to string before parsing.

This PR will close #166

### CODE REVIEW

File: src/packageParser.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ function loadAndParseFile( path ) {
 		throw new ReferenceError( 'File with given path does not exist.' );
 	}
 
-	const contents = readFileSync( path );
+	const contents = readFileSync( path ).toString();
```
Comment (Comandeer) [inline src/packageParser.js:21]: There is already some code doing such a conversion: https://github.com/Comandeer/rollup-lib-bundler/blob/d267bc6cfb9963ae0b3a354950073156238e2587/tests/bundler.js#L177

Due to the consistency it should be rather:

```suggestion
	const contents = readFileSync( path, 'utf8' );
```

**Comment by piecioshka** [comment]
Hi @Comandeer,
I updated changes.
